group_name: right_arm

benchmark_service: /benchmark_planning_problem
world_frame: base_footprint
robot_model_root_frame: odom_combined
spine_frame: torso_lift_joint
experiment_group_name: industrial
trajectory_description_for_display: interpolate
# of calls to the planner per experiment
average_count: 5

sbpl_planner_id: WAstar
ompl_planner_id: RRT

eps_file: eps_5

timeout_file: 20_timeout

exp_run_count: 1

epsilon: 5

goal_tolerance:
  xyz: 0.02 0.02 0.02
  rpy: 0.05 0.05 0.05

apply_offset_to_collision_objects: true

collision_object_offset:
  xyz: 0.06 -0.05 0.0
  rpy: 0 0 0

# true: use the last waypoint in the previous experiment's trajectory as the start state for the next experiment 
# false: use the start state specified in the experiment description as the start state of that experiment
use_current_pose_as_start_state: true

# only used for both_arms experiments
# this is currently needed to be on the param server for the single arm experiments as well :)
# pose of {r,l}_wrist_roll_links in the object frame
object_pose_in_gripper:
  right:
    xyz: -0.20 -0.1 0.0
    rpy: 0.0 0.0 0.0
  left:
    xyz: -0.20 0.1 0.0
    rpy: 0.0 0.0 0.0

initial_start_state:
  #right: -0.2 0.9223 -1.0472 -0.8 0.0 0.0 0.0
  right: -1.75 0.017997624551430391 -0.005238188295824564 -1.4 -0.00041708680445573521 -1.1 -0.0010002085575777642
  left: 1.5 1.0 0.005683010665493704 -1.4 0.00079943310185193195 -0.7439117804053561 0.00049889278955195238
  base: 0 0 0 
  spine: 0.2


