group_name: right_arm

benchmark_service: /benchmark_planning_problem
world_frame: base_footprint
robot_model_root_frame: odom_combined
spine_frame: torso_lift_joint
experiment_group_name: tunnel

# of calls to the planner per experiment
average_count: 5

sbpl_planner_id: Hstar
ompl_planner_id: RRT

eps_file: eps_5
epsilon: 5

exp_run_count: 20

timeout_file: 20_timeout

goal_tolerance:
  xyz: 0.02 0.02 0.02
  rpy: 0.05 0.05 0.05

# true: use the last waypoint in the previous experiment's trajectory as the start state for the next experiment 
# false: use the start state specified in the experiment description as the start state of that experiment
use_current_pose_as_start_state: true

apply_offset_to_collision_objects: false

# only used for both_arms experiments
# this is currently needed to be on the param server for the single arm experiments as well :)
# pose of {r,l}_wrist_roll_links in the object frame
object_pose_in_gripper:
  right:
    xyz: -0.20 -0.1 0.0
    rpy: 0.0 0.0 0.0
  left:
    xyz: -0.20 0.1 0.0
    rpy: 0.0 0.0 0.0

initial_start_state:
  right: -1.5 0.017997624551430391 -0.005238188295824564 -1.4 -0.00041708680445573521 -0.74471175505726084 -0.0010002085575777642
  left: 2.135, 0.803, 1.732, -1.905, 2.369, -1.680, 1.398
  base: 0 0 0 
  spine: 0.1


